FROM pytorch/pytorch
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends git
RUN apt-get install python3-pip -y

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    ffmpeg \
    libsm6 \
    libxext6 \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && pip --no-cache-dir install \
    Pillow \
    h5py \
    matplotlib \
    mock \
    pytorch3d \
    numpy \
    scipy \
    sympy \
    nose \
    sklearn \
    pandas \
    future \
    pyhocon\
    portpicker \
    PyMCubes \
    numba==0.48.0 \
    tqdm \
    imageio \
    imageio-ffmpeg \
    configargparse \
    scikit-image \
    opencv-python \
    visdom \
    tensorboard \
    dominate \
    cachetools \
    notebook
    
WORKDIR /nerf
EXPOSE  8888
EXPOSE  6666 
# Add Tini. Tini operates as a process subreaper for jupyter. This prevents kernel crashes.
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/nerf --ip 0.0.0.0  --allow-root"]